version: '3'

services:
  football_seasons:
    image: "football-seasons-17:00"
    build: .
    depends_on:
      - localhost
  localhost:
    image: "postgres:10"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: football_seasons_dev
      PGDATA: /var/lib/postgresql/data/pgdata
    restart: always
    volumes:
      - pgdata:/var/lib/postgresql

volumes:
  pgdata:
