apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:13.6
          imagePullPolicy: "IfNotPresent"
          ports:
          - containerPort: 5432
          envFrom:
            - configMapRef:
                name: football-seasons-config-map
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: postgresdata
      volumes:
        - name: postgresdata
          persistentVolumeClaim:
            claimName: postgres-persistent-volume
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-service
spec:
  type: NodePort 
  selector:
    app: postgres
  ports:
    - port: 5432
      nodePort: 30001
