apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-persistent-volume
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi
